version = 0.1
[default.deploy.parameters]
stack_name = "bolt-event-pipeline"
resolve_s3 = true
s3_prefix = "bolt-event-pipeline"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

